improvement: adds url, headers, test report

diff --git a/schema-check/action.yml b/schema-check/action.yml
--- a/schema-check/action.yml
+++ b/schema-check/action.yml
@@ -5,13 +5,21 @@ name: Schematest
 description: 'Schematest for API using schemathesis'
 
 inputs:
-  GITHUB_TOKEN:
-    description: 'Github Token'
-    required: false
   AUTH_TOKEN:
     description: 'Auth Token'
     required: false
-    default: 'xxxxx'
+    default: ''
+  SWAGGERPATH:
+    description: 'Swagger Path'
+    required: false
+    default: 'https://localhost:3000/swagger.json'
+  GITHUB_TOKEN:
+    description: 'Github Token'
+    required: false
+  XTFSO_LICENSE:
+    description: 'XTFSO License'
+    required: false
+    default: '82cf9f16-8366-48fc-96b0-2f683dea79bc;;'
 
 runs:
   using: 'composite'
@@ -25,12 +33,23 @@ runs:
         packages: |
           schemathesis
 
-    - name: Schemacheck
+    - name: Schemacheck (Auth)
+      if: inputs.AUTH_TOKEN
       id: schemacheck
-      with:
-        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
-        AUTH_TOKEN: ${{ inputs.AUTH_TOKEN }}
       run: | 
-         echo "GITHUB_TOKEN: $GITHUB_TOKEN"
-         echo "AUTH_TOKEN: $AUTH_TOKEN"
-         st run -H "Authorization: Bearer $AUTH_TOKEN" https://host.docker.internal:7047/swagger/v1/swagger.json --request-tls-verify=false --checks response_schema_conformance --wait-for-schema=5
+        echo "Running schemathesis with auth token"
+        st run -H "X-Tfso-License: ${{ inputs.XTFSO_LICENSE }}" -H "Authorization: Bearer ${{ inputs.AUTH_TOKEN }}" ${{ inputs.SWAGGERPATH }} --request-tls-verify=false --checks response_schema_conformance --wait-for-schema=5 --junit-xml=report.xml
+    
+    - name: Schemacheck (No Auth)
+      id: schemacheck
+      if: inputs.AUTH_TOKEN == ''
+      run: | 
+        echo "Running schemathesis without auth token"
+        st run -H "X-Tfso-License: ${{ inputs.XTFSO_LICENSE }}" ${{ inputs.SWAGGERPATH }} --request-tls-verify=false --checks response_schema_conformance --wait-for-schema=5 --junit-xml=report.xml
+      shell: bash
+
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'report.xml'
